# 认证流程的源码分析

1. 认证时，先进入 AbstractAuthenticationProcessingFilter 的 doFilter 方法

```java
private void doFilter(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws IOException, ServletException {
    // ...
        try {
            Authentication authenticationResult = this.attemptAuthentication(request, response);
            if (authenticationResult == null) {
                return;
            }

            // ...

            this.successfulAuthentication(request, response, chain, authenticationResult);
        } catch (InternalAuthenticationServiceException var5) {
            this.logger.error("An internal error occurred while trying to authenticate the user.", var5);
            this.unsuccessfulAuthentication(request, response, var5);
        } catch (AuthenticationException var6) {
            this.unsuccessfulAuthentication(request, response, var6);
        }

    }
}
```

里面主要包含认证成功后的 successfulAuthentication 流程和异常捕获后的 unsuccessfulAuthentication 流程。

2. 进入 UsernamePasswordAuthenticationFilter 的 attemptAuthentication 方法

```java
public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException {
        // ...
        return this.getAuthenticationManager().authenticate(authRequest);
}
```

3. 进入 ProviderManager 的 authenticate 方法

```java
public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    // ...

    while(var9.hasNext()) {
        AuthenticationProvider provider = (AuthenticationProvider)var9.next();
        if (provider.supports(toTest)) {
            // ...

            try {
                result = provider.authenticate(authentication);
                if (result != null) {
                    this.copyDetails(authentication, result);
                    break;
                }
            } catch (InternalAuthenticationServiceException | AccountStatusException var14) {
                this.prepareException(var14, authentication);
                throw var14;
            } catch (AuthenticationException var15) {
                lastException = var15;
            }
        }
    }

    if (result == null && this.parent != null) {
        try {
            parentResult = this.parent.authenticate(authentication);
            result = parentResult;
        } catch (ProviderNotFoundException var12) {
        } catch (AuthenticationException var13) {
            parentException = var13;
            lastException = var13;
        }
    }

    // ...
}
```

authenticate 流程：

- 调用 ```provider.authenticate(authentication)``` 进行认证（进入步骤 4），如果成功就跳出当前循环
- 捕获到异常时的处理（这一步非常重要，因为异常不同，处理流程也不同）
   - 当时捕获到 ```InternalAuthenticationServiceException | AccountStatusException``` 异常时，会抛出该异常
   - 当捕获到 ```AuthenticationException``` 异常时，后续流程会继续执行
- 当 result 为空的时候，说明认证流程返回的是null或是捕获到了 ```AuthenticationException``` 异常，此时会回调步骤 3

***重点：自定义的业务代码须抛出合适的异常。这一点非常重要！因为不同的异常会执行不同的流程从而得到不同的响应。***

- ***如果业务代码抛出了 BadCredentialsException 异常，result 的结果就是 ```null```，从而会再次回调该 authenticate 方法***
- ***如果业务代码抛出了 InternalAuthenticationServiceException 异常，就会因 ```throw var14``` 而跳出 authenticate 流程***

4. 进入 AbstractUserDetailsAuthenticationProvider 的 retrieveUser 方法

```java
public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    // ...
    UserDetails user = this.userCache.getUserFromCache(username);
    if (user == null) {
        cacheWasUsed = false;

        try {
            user = this.retrieveUser(username, (UsernamePasswordAuthenticationToken)authentication);
        } catch (UsernameNotFoundException var6) {
            this.logger.debug("Failed to find user '" + username + "'");
            if (!this.hideUserNotFoundExceptions) {
                throw var6;
            }

            throw new BadCredentialsException(this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.badCredentials", "Bad credentials"));
        }

        Assert.notNull(user, "retrieveUser returned null - a violation of the interface contract");
    }

    // ...
}
```

5. 转到自定义 MyAuthenticationProvider 的 retrieveUser 方法

```java
public class MyAuthenticationProvider extends AbstractUserDetailsAuthenticationProvider {
    // ...

    @Override
    protected void additionalAuthenticationChecks(UserDetails userDetails, UsernamePasswordAuthenticationToken authentication) throws AuthenticationException {
        // ...
        if (authentication.getCredentials() == null) {
            this.logger.debug("Failed to authenticate since no credentials provided");
            throw new InternalAuthenticationServiceException("无效的凭证");
        } else {
            String presentedPassword = authentication.getCredentials().toString();
            if (!this.passwordEncoder.matches(presentedPassword, userDetails.getPassword())) {
                this.logger.debug("Failed to authenticate since password does not match stored value");
                throw new InternalAuthenticationServiceException("用户名或密码错误");
            }
        }
    }

    @Override
    protected void doAfterPropertiesSet() {
        Assert.notNull(this.userDetailsService, "A UserDetailsService must be set");
    }

    @Override
    protected final UserDetails retrieveUser(String username, UsernamePasswordAuthenticationToken authentication) throws AuthenticationException {
        this.prepareTimingAttackProtection();
        // ...
        try {
            UserDetails loadedUser = this.getUserDetailsService().loadUserByUsername(username);
            if (loadedUser == null) {
                authentication.eraseCredentials();
                throw new UsernameNotFoundException("username is not exist");
            } else {
                return loadedUser;
            }
        } catch (UsernameNotFoundException var4) {
            this.mitigateAgainstTimingAttack(authentication);
            throw var4;
        } catch (InternalAuthenticationServiceException var5) {
            throw var5;
        } catch (Exception var6) {
            throw new InternalAuthenticationServiceException(var6.getMessage(), var6);
        } catch (Throwable t) {
            throw new InternalAuthenticationServiceException(t.getMessage(), t);
        }
    }
}
```

6. 转到自定义 MyDetailsService 的 loadUserByUsername

```java
public class MyDetailsService implements UserDetailsService {
    // ...

    @Override
    public UserDetails loadUserByUsername(String name) throws UsernameNotFoundException {
        // ...
        try {
            response = this.uaaFeign.getUserByUsername(loginVo);
        } catch (Exception ex) {
            log.error(ex.getMessage(), ex);
            loadUserFailure("访问服务失败");
        }
        if (response == null || !response.getCode().equals(0)) {
            // 注意（以下是通过调试源码得出的结论，仅作参考，如果有其他更好的解决方法也可以使用）：
            // 虽然该方法抛出的是UsernameNotFoundException
            // 但是通过调试源码得知，如果在此处抛出UsernameNotFoundException(response.getMsg())的话，源码内部会重新封装内置的BadCredentialsException并抛出，也就是异常信息统一都是固定的"Bad credentials"
            // 所以此处需要抛出new BadCredentialsException(response.getMsg())
            loadUserFailure(response.getMsg());
        }
        // ...
    }
}
```

7. 转到自定义 MyAuthenticationProvider 的 additionalAuthenticationChecks 方法验证密码

8. 如果有异常的话，就由步骤 3 的 ProviderManager 的 authenticate 捕获异常，然后根据异常的类型执行相应的后续流程

```java
public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    // ...

    while(var9.hasNext()) {
        AuthenticationProvider provider = (AuthenticationProvider)var9.next();
        if (provider.supports(toTest)) {
            // ...

            try {
                result = provider.authenticate(authentication);
                if (result != null) {
                    this.copyDetails(authentication, result);
                    break;
                }
            } catch (InternalAuthenticationServiceException | AccountStatusException var14) {
                this.prepareException(var14, authentication);
                throw var14;
            } catch (AuthenticationException var15) {
                lastException = var15;
            }
        }
    }

    // ...
}
```
